var spec={
    "45.32.71.204":"尼日利亚",
    "45.32.23.104":"澳大利亚",
    "45.32.22.107":"巴拿马",
    "112.54.244.18":"海南",
    "220.248.40.158":"上海",
    "124.65.183.98":"北京",
    "115.236.71.42":"浙江",
    "115.236.71.43":"浙江",
    "115.236.71.44":"浙江",
    "115.236.71.45":"浙江",
    "115.236.71.46":"浙江",
    "219.143.74.42":"北京"

}
var countryReflects={//一些关系映射
    /**特殊 字典 **/
    '国外':{f:'nations'},
    '成都信息工程学院':{c:'成都', f:'中国'},
    '中山大学':{c:'广东', f:'中国'},
    /**
     * 北美字典
     */
    '加利福尼亚':{c:'northAmerica',f:'美国'},
    '北美地区':{c:'northAmerica',f:'美国'},
    '弗吉尼亚':{c:'northAmerica',f:'美国'},
    '伯利兹':{c:'northAmerica'},
    '多米尼克':{c:'northAmerica'},
    '洛杉矶':{c:'northAmerica',f:'美国'},
    '新泽西':{c:'northAmerica',f:'美国'},

    '格陵兰岛':{c:'northAmerica',f:'丹麦'},
    '伯利兹城':{c:'northAmerica'},
    '加拿大':{c:'northAmerica'},
    '危地马拉':{c:'northAmerica'},
    '古巴':{c:'northAmerica'},
    '哥斯达黎加':{c:'northAmerica'},
    '圣卢西亚':{c:'northAmerica'},
    '圣基茨和尼维斯':{c:'northAmerica'},
    '圣文森特和格林纳丁斯':{c:'northAmerica'},
    '墨西哥':{c:'northAmerica'},
    '多米尼加':{c:'northAmerica'},
    '多米尼加共和国':{c:'northAmerica'},
    '安提瓜和巴布达':{c:'northAmerica'},
    '尼加拉瓜':{c:'northAmerica'},
    '巴哈马群岛':{c:'northAmerica'},
    '巴拿马':{c:'northAmerica'},
    '波多黎各':{c:'northAmerica'},
    '洪都拉斯':{c:'northAmerica'},
    '海地':{c:'northAmerica'},
    '牙买加':{c:'northAmerica'},
    '特立尼达和多巴哥':{c:'northAmerica'},
    '百慕大':{c:'northAmerica'},
    '美国':{c:'northAmerica'},
    '萨尔瓦多':{c:'northAmerica'},
    '锡佩德罗密 ':{c:'northAmerica'},
    '圣文森特和格林纳丁斯 ':{c:'northAmerica'},


    /**
     * 南美字典
     */
    '巴巴多斯':{c:'southAmerica'},
    '巴哈马':{c:'southAmerica'},
    '苏里南':{c:'southAmerica'},

    '乌拉圭':{c:'southAmerica'},
    '厄瓜多尔':{c:'southAmerica'},
    '哥伦比亚':{c:'southAmerica'},
    '圭亚那':{c:'southAmerica'},
    '委内瑞拉':{c:'southAmerica'},
    '巴拉圭':{c:'southAmerica'},
    '巴西':{c:'southAmerica'},
    '智利':{c:'southAmerica'},
    '玻利维亚':{c:'southAmerica'},
    '秘鲁':{c:'southAmerica'},
    '苏里南共和国':{c:'southAmerica'},
    '阿根廷':{c:'southAmerica'},
    '马尔维纳斯群岛 ':{c:'southAmerica'},


    /**
     * 欧洲字典
     */
    '拉脱维亚':{c:'europe'},
    '冰岛':{c:'europe'},
    '匈牙利':{c:'europe'},
    '卢森堡':{c:'europe'},
    '捷克':{c:'europe'},
    '法国':{c:'europe'},
    '波兰':{c:'europe'},
    '英国':{c:'europe'},
    '欧洲':{c:'europe',f:'default'},

    '丹麦':{c:'europe'},
    '乌克兰':{c:'europe'},
    '伊斯兰迪亚':{c:'europe'},
    '俄罗斯':{c:'europe'},
    '保加利亚':{c:'europe'},
    '克罗地亚':{c:'europe'},
    '共和切卡':{c:'europe'},
    '列支敦士登':{c:'europe'},
    '卢森博格':{c:'europe'},
    '圣马力诺共和国':{c:'europe'},
    '塞尔维亚':{c:'europe'},
    '塞浦路斯':{c:'europe'},
    '奥地利':{c:'europe'},
    '安道尔共和国':{c:'europe'},
    '希腊':{c:'europe'},
    '弗兰克':{c:'europe'},
    '弗朗西亚':{c:'europe'},
    '德国':{c:'europe'},
    '意大利':{c:'europe'},
    '拉脱维亚共和国':{c:'europe'},
    '挪威':{c:'europe'},
    '摩尔多瓦':{c:'europe'},
    '摩纳哥':{c:'europe'},
    '斯洛伐克共和国':{c:'europe'},
    '斯洛文尼亚':{c:'europe'},
    '格拉纳达':{c:'europe',f:'西班牙'},
    '格鲁吉亚':{c:'europe'},
    '梵蒂冈城':{c:'europe'},
    '欧洲联盟':{c:'europe'},
    '比利时':{c:'europe'},
    '波斯尼亚和黑塞哥维那':{c:'europe'},
    '波罗尼亚':{c:'europe'},
    '爱尔兰':{c:'europe'},
    '爱沙尼亚':{c:'europe'},
    '瑞典':{c:'europe'},
    '瑞士':{c:'europe'},
    '白俄罗斯':{c:'europe'},
    '立陶宛':{c:'europe'},
    '罗马尼亚':{c:'europe'},
    '芬兰':{c:'europe'},
    '英国 ':{c:'europe'},
    '荷兰':{c:'europe'},
    '葡萄牙':{c:'europe'},
    '西班牙':{c:'europe'},
    '阿尔巴尼亚':{c:'europe'},
    '马其顿':{c:'europe'},
    '马耳他':{c:'europe'},
    '黑山共和国':{c:'europe'},


    /**
     * 亚洲字典
     */
    '香港':{c:'asia',f:'中国'},
    '阿联酋':{c:"asia"},
    '土耳其':{c:'asia'},
    '菲律宾':{c:'asia'},
    '孟加拉':{c:'asia'},
    '亚太地区':{c:'asia',f:'default'},
    '东华大学':{c:'asia', f:'上海'},
    '澳门':{c:'asia',f:'中国'},
    '台湾':{c:'asia',f:'中国'},
    '不丹':{c:'asia'},
    '东帝汶':{c:'asia'},
    '中国':{c:'asia'},
    '乌兹别克斯坦':{c:'asia'},
    '也门':{c:'asia'},
    '以色列':{c:'asia'},
    '伊拉克共和国':{c:'asia'},
    '伊朗':{c:'asia'},
    '卡塔尔':{c:'asia'},
    '印度':{c:'asia'},
    '印度尼西亚':{c:'asia'},
    '叙利亚共和国':{c:'asia'},
    '吉尔吉斯斯坦':{c:'asia'},
    '哈萨克斯坦':{c:'asia'},
    '土库曼斯坦':{c:'asia'},
    '塔吉克斯坦':{c:'asia'},
    '孟加拉国':{c:'asia'},
    '尼泊尔':{c:'asia'},
    '巴勒斯坦':{c:'asia'},
    '巴基斯坦':{c:'asia'},
    '巴林':{c:'asia'},
    '斯里兰卡':{c:'asia'},
    '新加坡':{c:'asia'},
    '日本':{c:'asia'},
    '朝鲜':{c:'asia'},
    '柬埔寨':{c:'asia'},
    '沙特阿拉伯':{c:'asia'},
    '泰国':{c:'asia'},
    '科威特':{c:'asia'},
    '约旦':{c:'asia'},
    '缅甸':{c:'asia'},
    '老挝':{c:'asia'},
    '菲律宾共和国':{c:'asia'},
    '蒙古':{c:'asia'},
    '越南':{c:'asia'},
    '阿塞拜疆':{c:'asia'},
    '阿富汗':{c:'asia'},
    '阿拉伯联合酋长国':{c:'asia'},
    '阿曼':{c:'asia'},
    '韩国':{c:'asia'},
    '马尔代夫':{c:'asia'},
    '马来西亚':{c:'asia'},
    '黎巴嫩':{c:'asia'},


    /**
     * 大洋洲字典
     */
    '印尼':{c:'oceania'},
    '图瓦卢':{c:'oceania'},
    '基里巴斯':{c:'oceania'},
    '密克罗尼西亚':{c:'oceania'},
    '巴布亚新几内亚':{c:'oceania'},
    '帕劳':{c:'oceania'},
    '所罗门群岛':{c:'oceania'},
    '斐济':{c:'oceania'},
    '新西兰':{c:'oceania'},
    '汤加':{c:'oceania'},
    '澳大利亚':{c:'oceania'},
    '瑙鲁':{c:'oceania'},
    '瓦努阿图':{c:'oceania'},
    '萨摩亚群岛':{c:'oceania'},
    '马绍尔群岛':{c:'oceania'},


    /**
     * 非洲
     */
    '中非共和国':{c:'africa'},
    '乌干达':{c:'africa'},
    '乍得':{c:'africa'},
    '佛得角':{c:'africa'},
    '冈比亚':{c:'africa'},
    '几内亚':{c:'africa'},
    '几内亚比绍':{c:'africa'},
    '刚果':{c:'africa'},
    '刚果民主共和国':{c:'africa'},
    '利比亚':{c:'africa'},
    '利比里亚':{c:'africa'},
    '加纳':{c:'africa'},
    '加蓬':{c:'africa'},
    '南非':{c:'africa'},
    '博茨瓦纳':{c:'africa'},
    '卢旺达':{c:'africa'},
    '厄立特里亚':{c:'africa'},
    '吉布提':{c:'africa'},
    '喀麦隆':{c:'africa'},
    '圣多美和普林西比':{c:'africa'},
    '坦桑尼亚':{c:'africa'},
    '埃及':{c:'africa'},
    '埃塞俄比亚':{c:'africa'},
    '塞内加尔':{c:'africa'},
    '塞拉利昂':{c:'africa'},
    '塞舌尔':{c:'africa'},
    '多哥':{c:'africa'},
    '安哥拉':{c:'africa'},
    '尼日利亚':{c:'africa'},
    '尼日尔':{c:'africa'},
    '布基纳法索':{c:'africa'},
    '布隆迪':{c:'africa'},
    '摩洛哥':{c:'africa'},
    '斯威士兰':{c:'africa'},
    '毛里塔尼亚':{c:'africa'},
    '毛里求斯':{c:'africa'},
    '津巴布韦':{c:'africa'},
    '科摩罗':{c:'africa'},
    '科特迪瓦':{c:'africa'},
    '突尼斯':{c:'africa'},
    '索马里':{c:'africa'},
    '纳米比亚':{c:'africa'},
    '肯尼亚':{c:'africa'},
    '苏丹':{c:'africa'},
    '莫桑比克':{c:'africa'},
    '莱索托':{c:'africa'},
    '贝宁':{c:'africa'},
    '赞比亚':{c:'africa'},
    '赤道几内亚':{c:'africa'},
    '阿尔及利亚':{c:'africa'},
    '马拉维':{c:'africa'},
    '马达加斯加':{c:'africa'},
    '马里':{c:'africa'}
};
